language: node_js
node_js: node
dist: trusty
sudo: required
addons:
  chrome: stable
cache:
  yarn: true
  directories:
  - node_modules
install:
- yarn install
script:
- yarn test
deploy:
  provider: releases
  api_key:
    secure: Rkyjh/ZNQbCHZ/RpBHkO+ky1PBzz8K0Wz6Ie75uOpL45LV3I6N6ELd8vgdAIA/5ppMtF6ZpZ/Aul9Il48zIMLkcAv4pO69jQC7ysEcA0k0kZevDu7Bm41Yiwq4BKqsUsWQNz32y1Cuqq36zMwSjfzkX1v9vLVqxqvu8ohPAKeCDd8R+PCy1q8Rk1lvfH9sHXV/KMyjxXH3GBHNDoSsem/dQy3DlhXqtypDWPdXDFhbxwbs4PTvQuu+BVDiDtVcvhxrg7xd7J1lxYG9AMUFyB0PzDGXzIsHIUhhpcR5tsem8hWgIfl73SWZsWsCpi3DCJ/LB8rtavhKz6gKmNT1tBLGi6GsEN4Xdt2hTOvKCnMlhwynRZjL6cX438TrobUZH37AucTmORA0SpcbhuqbzD5z44e+PK3hj41gWOQJiiinkPffNT0gn2nPo1OY8a4Bc2OCLG0uWSr26k/5wC9PsdPjejsNCG74JR3kTY6K16uSk+YPrsvS997/RCuj2g6mfpQta5KbNtBfVjjXli8BO7GNdDkUqWKtql7l4ie/RqFbxuSLtjUHqF3O1JxjUhG8JjXcLOz72/e2SL6uaTBgbcC22jr+L7XbTtlfACu2mV6gKoAE0klpnFhOBGrivl5bUyHVTJ3tgau3kb9QfvCVtED3/kR/Eig31LLPBJmIWYe2M=
  file: dist/modl.min.js
  on:
    tags: true
