language: node_js
node_js: node
dist: trusty
sudo: required
addons:
  chrome: stable
cache:
  yarn: true
  directories:
  - node_modules
install:
- yarn install
script:
- yarn test
deploy:
  provider: npm
  email: ivan@sieder.xyz
  api_key:
    secure: GF6S4E3GSyaTi3UA2aig0Vy/bVFA46jf4vsnwR69hTRGRNy9lJQTHbWtfWOfpWC4n+5c3GPjImDKRQUOMSu708QN7T5bOhJ5nNJNcR0LuFof4an2oQLCIusn9pP0VNU8gyUYiXtrQ+MU5Jjq5o4XwaGxBNr5irJpbO3CwXo9DqMHnleuFS3cP1v8jUgDxqk08sAJgYK7R7kDEA3uvB2N5d4rnjLyAblKko8VRLe3JoaDNFSYc5lyiYzuG8fY8C/fy4WZiV9A6T65fJ4JjT41Hbm8gCtvYfRzfKRkMLcbMAJL2v9yUbI6xoHIeRMOR0F7citoGUXfIHUxWLcFivAbJZACfjqfG3mPGm1ZvZfyP08u02Qs3ImtdYRWyCyHj6Ks0X5e+6sR5vymBwn0vTvsPztHQ0zOGdMuo2lUWrpdHJR9IqQL50ffJzMIzt297w9AxsCFxIbeG3dgTrexnhqIoWU6N4pMaq6XmIlXQDm5W0VpNrkXuBwkn7SyRUFhLq2uqJE8ZFEYGCEuW8ymdcnOwbVLhcGPBwwTGVSq7Tjlw7Twzvkt+vnigfy05F70g2OkTWoQ2EozmgtZ5MLUVbOkH9KKDs5FQnse7Pj9Wm/tuQLYkcP/WVArVgDzXIFz7tb/BAfpw73Y0C8EX1ZUhU2mWIrWuOLSULcSCszRq48gnB8=
  on:
    tags: true
    repo: simedia-tech/modl-js
