language: node_js
node_js: node
dist: trusty
sudo: required
addons:
  chrome: stable
cache:
  yarn: true
  directories:
  - node_modules
deploy:
  provider: npm
  email: ivan@sieder.xyz
  api_key:
    secure: QVbF8LoZPZ7uDVx7umQWPTh/cbGj1AlTLlQtJaow4poe69eJdN+oSSC2Eov4Nizwn26ZWgF3sZ+Ll5SnSDbFRAklPHJjjjtBV8pTe52pTaNF7wXfKJtfoXlj4rNcudYz+3Y4kqc4tcIhXm4irvaR6OKMW17SRFfw2Z8WKBQUAZ+AzWXdxi/jHKaQLvHNBWf6w7ngZIhoOF6KMPqQs0pTOKC9WzmWBKbW668H0AukFjLYP5Hi1vu+ZFUQAMJuUtR9shxxeFrc7Jrwi7s81AX7ZTV/+lcUt9cwgvtGY7vLed3JEb2+D362Wt3C9jiH3NhY+UcLes5/6T/RGcYlG6QxEWVghyOhcOD58Q+JRpbqZwnvAKdQJ1yKxlV+ywk3EMs1uZgen64piRho0oxtt8vIG2Py+FNe8I/unDXZ1NY9VjFgTiFDnzfjBqMeizEuOQuELUQ1DDdJ8uUn9veoNSksjW1lKqca1zryrr5nXgCdJChKBYe6yOV2/GjmeGU95cDPQ2F0YIC96BdW3uodNDAQGlghH0BA4T+auvZr+RgAdACHmsHHVp+SyWRBiYOQIgT+A2PzfAYTmYogn+OtNfNuHlae1TE2ZWRC3i8syd+yFJ4jehlmvitFCqOZnc9nQp7sP9NJVUcqGuHu43KmlKTM/z92TFC6I+guBG0Qd2kSaDc=
  skip_cleanup: true
  on:
    tags: true
    repo: simedia-tech/modl-js
