language: node_js
node_js: node
dist: trusty
sudo: required
addons:
  chrome: stable
cache:
  yarn: true
  directories:
  - node_modules
install:
- yarn install
script:
- yarn test
deploy:
  provider: npm
  email: ivan@sieder.xyz
  api_key:
    secure: F/2jurHDOW3tqSycxca1QpJ9iYohIqAxEoiSGMA+WtRWAeO9SVpEbPkg3He1udCS9ejb6ikk7w96QRelN1lPM1mz+33M0/24PAL2IvnKHITnZ6oEvlc+qRF3wDNfZxQbxkVTsE53V7GFv6gSLk+bqj8++WEgXri/u5mul+BwTG/K04hH1APSB5seh2oRmGrvBhDo/o3n6TQvcqY+11EJUPAeT1XrRAcypENVThyKV1DXd/9JIrGr5jdJSFYjFx94TrVxctZjJfBr62LsqU5MXyL3PtC63GeVqZTp0ItN/EPZ8R5EtIUruu4esnVeWbhcUlMwGKsdUlR7FphK5ZMOMrf3YJFcxMYIRwLmRuHO/4kR/iiM1Df38qZD55Bsxe7COb22AL3q/kOMWsAG3KCX4pdxRKpYcnMJvbUjUSAV2I21jFCwYsrC6aO/ETbS+iPvkdJBofINrylJV1b5G+FospmqvxiFRC3L1KHMjqY4KmEHpqnl7v8EaZwlUUdJ1uw191YuS83MaoVqKkeGzSUQU/hrTIFS7FEqrF0qJxk17Q6I2X2pLxMsB4GZehBBNDWR8FgvmKo/bobCD5RNzg1UbuNTFmgC+gMZNasENX77RVcIWrky1P6OUiK9hBZj6PNYPlilBQ7s868Vm7AEM4xMXRlfQr4jRUnjfQgLiSBwcnM=
  on:
    tags: true
    repo: simedia-tech/modl-js
